/*
 * Lights Out pure logic, size-agnostic (3x3..NxN).
 *
 * Board representation: a flat boolean array of length size*size where
 * `true` means the cell's light is ON. Pressing a cell toggles it and its
 * orthogonal neighbors (the classic plus-shape).
 *
 * Solvability: boards are generated by toggling random cells starting from
 * the all-OFF state. Because each press is its own inverse, replaying the
 * same set of presses solves the board, so generated boards are always
 * solvable.
 */

export type LightsOutBoard = {
  readonly cells: readonly boolean[];
  readonly size: number;
};

const NEIGHBOR_DELTAS: ReadonlyArray<readonly [number, number]> = [
  [0, 0],
  [-1, 0],
  [1, 0],
  [0, -1],
  [0, 1],
];

const indexOf = (row: number, col: number, size: number): number =>
  row * size + col;

const inBounds = (row: number, col: number, size: number): boolean =>
  row >= 0 && row < size && col >= 0 && col < size;

export const createEmptyLightsOutBoard = (size: number): LightsOutBoard => {
  if (!Number.isInteger(size) || size < 2) {
    throw new Error(`invalid lights-out board size: ${size}`);
  }
  return { cells: new Array<boolean>(size * size).fill(false), size };
};

/**
 * Returns a new board with the press at (row, col) applied: that cell and
 * its 4 orthogonal neighbors are toggled. Throws if (row, col) is OOB.
 */
export const pressLightsOut = (
  board: LightsOutBoard,
  row: number,
  col: number,
): LightsOutBoard => {
  const { size } = board;
  if (!inBounds(row, col, size)) {
    throw new Error(`lights-out press out of bounds: (${row}, ${col})`);
  }
  const next = board.cells.slice();
  for (const [dr, dc] of NEIGHBOR_DELTAS) {
    const r = row + dr;
    const c = col + dc;
    if (!inBounds(r, c, size)) continue;
    const i = indexOf(r, c, size);
    next[i] = !next[i];
  }
  return { cells: next, size };
};

/** Returns true if every light is OFF. */
export const isLightsOutSolved = (board: LightsOutBoard): boolean =>
  board.cells.every((on) => !on);

/**
 * Generates a solvable board by applying `presses` random presses to an
 * empty board. Picks distinct cells when possible (pressing the same cell
 * twice cancels out, which would wastefully reduce difficulty). If the
 * resulting board is already solved (e.g. presses == 0 or unlucky cancels),
 * one extra press is applied so the player has something to do.
 */
export const generateLightsOutBoard = (
  size: number,
  presses: number,
  random: () => number = Math.random,
): LightsOutBoard => {
  const total = size * size;
  let board = createEmptyLightsOutBoard(size);
  const used = new Set<number>();
  const cap = Math.min(presses, total);

  for (let k = 0; k < cap; k++) {
    let idx = Math.floor(random() * total);
    // Best-effort distinct picks; bail out after a few tries to keep this
    // bounded rather than risking a long loop on small boards.
    for (let attempt = 0; attempt < 8 && used.has(idx); attempt++) {
      idx = Math.floor(random() * total);
    }
    used.add(idx);
    const r = Math.floor(idx / size);
    const c = idx % size;
    board = pressLightsOut(board, r, c);
  }

  if (isLightsOutSolved(board)) {
    board = pressLightsOut(board, 0, 0);
  }
  return board;
};
