export {
  GAME_2048_SIZE,
  addRandomTile,
  boardFromState,
  commitMerges,
  createEmptyBoard,
  createInitialState,
  isGameOver,
  moveState,
  type Game2048Board,
  type Game2048Direction,
  type Game2048MoveResult,
  type Game2048State,
  type Game2048Tile,
} from "./game";
